version: '3'
services:
  event-log-reader:
    build:
      context: .
      dockerfile: Dockerfile-dev
    volumes:
    - .:/go/src/github.com/tobyjsullivan/event-log-reader
    ports:
    - "6300:3000"
    depends_on:
    - "logs-db"
    - "event-reader"
    - "redis"
    environment:
    - EVENT_READER_API=http://event-reader:3000/
    - PG_HOSTNAME=logs-db
    - PG_USERNAME=postgres
    - PG_PASSWORD=pass1234
    - PG_DATABASE=postgres
    - REDIS_HOSTNAME=redis
    - REDIS_PORT=6379
    - REDIS_PASSWORD=
  redis:
    image: redis:3.0
    volumes:
    - ./data/redis:/data
  event-log:
    image: tobyjsullivan/event-log:1.0
    ports:
    - "6301:3000"
    depends_on:
    - "logs-db"
    - "event-store"
    environment:
    - EVENT_STORE_API=http://event-store:3000/
    - PG_HOSTNAME=logs-db
    - PG_USERNAME=postgres
    - PG_PASSWORD=pass1234
    - PG_DATABASE=postgres
  logs-db:
    image: tobyjsullivan/logs-db:1.0
    environment:
    - POSTGRES_PASSWORD=pass1234
    volumes:
    - ./data/logs-db:/var/lib/postgresql/data
  event-reader:
    image: tobyjsullivan/event-reader:3.0
    ports:
    - "6302:3000"
    env_file:
    - ./env/event-reader.env
  event-store:
    image: tobyjsullivan/event-store:3.0
    ports:
    - "6303:3000"
    env_file:
    - ./env/event-store.env

