FROM golang

RUN ["go", "get", "github.com/codegangsta/gin"]

VOLUME ["/go/src/github.com/tobyjsullivan/event-log-reader"]

EXPOSE 3000

WORKDIR /go/src/github.com/tobyjsullivan/event-log-reader

CMD ["gin"]

